//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aparencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aparencia()
        {
            this.Personagens = new HashSet<Personagem>();
        }
    
        public int IdAparencia { get; set; }
        public decimal Peso { get; set; }
        public decimal Altura { get; set; }
        public string EstiloCabelo { get; set; }
        public int CorOlho { get; set; }
        public int CorCabelo { get; set; }
        public int CorPele { get; set; }
        public string Nome { get; set; }
    
        public virtual Cor Cor { get; set; }
        public virtual Cor Cor1 { get; set; }
        public virtual Cor Cor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personagem> Personagens { get; set; }
    }
}
