//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personagem
    {
        public int IdPersonagem { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNasc { get; set; }
        public int Nivel { get; set; }
        public string Sexo { get; set; }
        public int RacaID { get; set; }
        public int SubclasseID { get; set; }
        public int AparenciaID { get; set; }
        public int AtributoID { get; set; }
        public int HabilidadeID { get; set; }
    
        public virtual Aparencia Aparencia { get; set; }
        public virtual Atributo Atributo { get; set; }
        public virtual Habilidade Habilidade { get; set; }
        public virtual Raca Raca { get; set; }
        public virtual Subclasse Subclasse { get; set; }
    }
}
